    <html>
    <head>
<style>
.failure {
background-color: orangered;
}
.success {
background-color: springgreen;
}
</style>
    </head>
    <body>
	<h1>Testing logs for Python</h1>
	<p>Running at Mon Jan  6 01:58:33 PM EST 2025</p>
  <div id="summary0" class="failure">
    <h2><a href="python_logs.html#pythonlog0">Assignment 0</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog0-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog0-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary1" class="failure">
    <h2><a href="python_logs.html#pythonlog1">Assignment 1</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog1-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog1-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary2" class="failure">
    <h2><a href="python_logs.html#pythonlog2">Assignment 2</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog2-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog2-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary3" class="failure">
    <h2><a href="python_logs.html#pythonlog3">Assignment 3</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog3-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog3-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary4" class="failure">
    <h2><a href="python_logs.html#pythonlog4">Assignment 4</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog4-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog4-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary5" class="failure">
    <h2><a href="python_logs.html#pythonlog5">Assignment 5</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog5-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog5-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary6" class="failure">
    <h2><a href="python_logs.html#pythonlog6">Assignment 6</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog6-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog6-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary7" class="failure">
    <h2><a href="python_logs.html#pythonlog7">Assignment 7</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog7-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog7-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary8" class="failure">
    <h2><a href="python_logs.html#pythonlog8">Assignment 8</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog8-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog8-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary9" class="failure">
    <h2><a href="python_logs.html#pythonlog9">Assignment 9</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog9-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog9-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary10" class="failure">
    <h2><a href="python_logs.html#pythonlog10">Assignment 10</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog10-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog10-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary11" class="failure">
    <h2><a href="python_logs.html#pythonlog11">Assignment 11</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog11-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog11-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary12" class="failure">
    <h2><a href="python_logs.html#pythonlog12">Assignment 12</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog12-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog12-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary13" class="failure">
    <h2><a href="python_logs.html#pythonlog13">Assignment 13</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog13-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog13-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary14" class="failure">
    <h2><a href="python_logs.html#pythonlog14">Assignment 14</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog14-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog14-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary15" class="failure">
    <h2><a href="python_logs.html#pythonlog15">Assignment 15</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog15-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog15-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary16" class="failure">
    <h2><a href="python_logs.html#pythonlog16">Assignment 16</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog16-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog16-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary17" class="failure">
    <h2><a href="python_logs.html#pythonlog17">Assignment 17</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog17-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog17-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary18" class="failure">
    <h2><a href="python_logs.html#pythonlog18">Assignment 18</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog18-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog18-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary19" class="failure">
    <h2><a href="python_logs.html#pythonlog19">Assignment 19</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog19-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog19-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary20" class="failure">
    <h2><a href="python_logs.html#pythonlog20">Assignment 20</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog20-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog20-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary21" class="failure">
    <h2><a href="python_logs.html#pythonlog21">Assignment 21</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog21-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog21-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary22" class="failure">
    <h2><a href="python_logs.html#pythonlog22">Assignment 22</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog22-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog22-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary23" class="failure">
    <h2><a href="python_logs.html#pythonlog23">Assignment 23</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog23-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog23-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary24" class="failure">
    <h2><a href="python_logs.html#pythonlog24">Assignment 24</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog24-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog24-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary25" class="failure">
    <h2><a href="python_logs.html#pythonlog25">Assignment 25</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog25-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog25-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary26" class="failure">
    <h2><a href="python_logs.html#pythonlog26">Assignment 26</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog26-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog26-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary27" class="failure">
    <h2><a href="python_logs.html#pythonlog27">Assignment 27</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog27-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog27-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary28" class="failure">
    <h2><a href="python_logs.html#pythonlog28">Assignment 28</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog28-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog28-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary29" class="failure">
    <h2><a href="python_logs.html#pythonlog29">Assignment 29</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog29-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog29-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary30" class="failure">
    <h2><a href="python_logs.html#pythonlog30">Assignment 30</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog30-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog30-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary31" class="failure">
    <h2><a href="python_logs.html#pythonlog31">Assignment 31</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog31-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog31-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary32" class="failure">
    <h2><a href="python_logs.html#pythonlog32">Assignment 32</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog32-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog32-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary33" class="failure">
    <h2><a href="python_logs.html#pythonlog33">Assignment 33</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog33-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog33-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary34" class="failure">
    <h2><a href="python_logs.html#pythonlog34">Assignment 34</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog34-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog34-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary35" class="failure">
    <h2><a href="python_logs.html#pythonlog35">Assignment 35</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog35-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog35-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary36" class="failure">
    <h2><a href="python_logs.html#pythonlog36">Assignment 36</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog36-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog36-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary37" class="failure">
    <h2><a href="python_logs.html#pythonlog37">Assignment 37</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog37-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog37-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary38" class="failure">
    <h2><a href="python_logs.html#pythonlog38">Assignment 38</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog38-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog38-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary39" class="failure">
    <h2><a href="python_logs.html#pythonlog39">Assignment 39</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog39-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog39-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary40" class="failure">
    <h2><a href="python_logs.html#pythonlog40">Assignment 40</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog40-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog40-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary41" class="failure">
    <h2><a href="python_logs.html#pythonlog41">Assignment 41</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog41-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog41-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary42" class="failure">
    <h2><a href="python_logs.html#pythonlog42">Assignment 42</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog42-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog42-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary43" class="failure">
    <h2><a href="python_logs.html#pythonlog43">Assignment 43</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog43-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog43-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary44" class="failure">
    <h2><a href="python_logs.html#pythonlog44">Assignment 44</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog44-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog44-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary45" class="failure">
    <h2><a href="python_logs.html#pythonlog45">Assignment 45</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog45-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog45-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary46" class="failure">
    <h2><a href="python_logs.html#pythonlog46">Assignment 46</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog46-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog46-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary47" class="failure">
    <h2><a href="python_logs.html#pythonlog47">Assignment 47</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog47-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog47-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary48" class="failure">
    <h2><a href="python_logs.html#pythonlog48">Assignment 48</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog48-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog48-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary49" class="failure">
    <h2><a href="python_logs.html#pythonlog49">Assignment 49</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog49-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog49-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary50" class="failure">
    <h2><a href="python_logs.html#pythonlog50">Assignment 50</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog50-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog50-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary51" class="failure">
    <h2><a href="python_logs.html#pythonlog51">Assignment 51</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog51-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog51-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary52" class="failure">
    <h2><a href="python_logs.html#pythonlog52">Assignment 52</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog52-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog52-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary53" class="failure">
    <h2><a href="python_logs.html#pythonlog53">Assignment 53</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog53-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog53-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary54" class="failure">
    <h2><a href="python_logs.html#pythonlog54">Assignment 54</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog54-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog54-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary55" class="failure">
    <h2><a href="python_logs.html#pythonlog55">Assignment 55</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog55-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog55-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary56" class="failure">
    <h2><a href="python_logs.html#pythonlog56">Assignment 56</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog56-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog56-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary57" class="failure">
    <h2><a href="python_logs.html#pythonlog57">Assignment 57</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog57-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog57-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary58" class="failure">
    <h2><a href="python_logs.html#pythonlog58">Assignment 58</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog58-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog58-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary59" class="failure">
    <h2><a href="python_logs.html#pythonlog59">Assignment 59</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog59-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog59-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary60" class="failure">
    <h2><a href="python_logs.html#pythonlog60">Assignment 60</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog60-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog60-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary61" class="failure">
    <h2><a href="python_logs.html#pythonlog61">Assignment 61</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog61-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog61-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary62" class="failure">
    <h2><a href="python_logs.html#pythonlog62">Assignment 62</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog62-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog62-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary63" class="failure">
    <h2><a href="python_logs.html#pythonlog63">Assignment 63</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog63-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog63-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary64" class="failure">
    <h2><a href="python_logs.html#pythonlog64">Assignment 64</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog64-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog64-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary65" class="failure">
    <h2><a href="python_logs.html#pythonlog65">Assignment 65</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog65-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog65-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary66" class="failure">
    <h2><a href="python_logs.html#pythonlog66">Assignment 66</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog66-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog66-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary67" class="failure">
    <h2><a href="python_logs.html#pythonlog67">Assignment 67</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog67-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog67-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary68" class="failure">
    <h2><a href="python_logs.html#pythonlog68">Assignment 68</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog68-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog68-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary69" class="failure">
    <h2><a href="python_logs.html#pythonlog69">Assignment 69</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog69-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog69-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary70" class="failure">
    <h2><a href="python_logs.html#pythonlog70">Assignment 70</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog70-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog70-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary71" class="failure">
    <h2><a href="python_logs.html#pythonlog71">Assignment 71</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog71-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog71-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary72" class="failure">
    <h2><a href="python_logs.html#pythonlog72">Assignment 72</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog72-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog72-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary73" class="failure">
    <h2><a href="python_logs.html#pythonlog73">Assignment 73</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog73-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog73-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary74" class="failure">
    <h2><a href="python_logs.html#pythonlog74">Assignment 74</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog74-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog74-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary75" class="failure">
    <h2><a href="python_logs.html#pythonlog75">Assignment 75</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog75-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog75-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary76" class="failure">
    <h2><a href="python_logs.html#pythonlog76">Assignment 76</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog76-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog76-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary77" class="failure">
    <h2><a href="python_logs.html#pythonlog77">Assignment 77</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog77-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog77-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary78" class="failure">
    <h2><a href="python_logs.html#pythonlog78">Assignment 78</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog78-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog78-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary79" class="failure">
    <h2><a href="python_logs.html#pythonlog79">Assignment 79</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog79-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog79-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary80" class="failure">
    <h2><a href="python_logs.html#pythonlog80">Assignment 80</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog80-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog80-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary81" class="failure">
    <h2><a href="python_logs.html#pythonlog81">Assignment 81</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog81-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog81-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary82" class="failure">
    <h2><a href="python_logs.html#pythonlog82">Assignment 82</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog82-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog82-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary83" class="failure">
    <h2><a href="python_logs.html#pythonlog83">Assignment 83</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog83-checkscaffold">error</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog83-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary84" class="failure">
    <h2><a href="python_logs.html#pythonlog84">Assignment 84</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog84-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog84-runanswer">error</a></li>
      </ul>
    </p>
  </div>
  <div id="summary85" class="failure">
    <h2><a href="python_logs.html#pythonlog85">Assignment 85</a> </h2>
    <p>
      <ul>
        <li> Check Scaffold : <a href="python_logs.html#pythonlog85-checkscaffold">success</a></li>
        <li> Run Answer : <a href="python_logs.html#pythonlog85-runanswer">error</a></li>
      </ul>
    </p>
  </div>
    <div id="pythonlog0" class="logdetails">
      <h2>Assignment 0 full log</h2>
    
<div class="success">
<h3 id="pythonlog0-checkscaffold">Check Scaffold for Assignment 0</h3>
<pre><code>Guessing setup.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog0-runanswer">Run Answer for Assignment 0</h3>
<pre><code>Guessing setup.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/0-Setup/python_answer/setup.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/0-Setup/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog1" class="logdetails">
      <h2>Assignment 1 full log</h2>
    
<div class="success">
<h3 id="pythonlog1-checkscaffold">Check Scaffold for Assignment 1</h3>
<pre><code>Guessing ListIMDB.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog1-runanswer">Run Answer for Assignment 1</h3>
<pre><code>Guessing ListIMDB.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/1-ListIMDB/python_answer/ListIMDB.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/1-ListIMDB/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog2" class="logdetails">
      <h2>Assignment 2 full log</h2>
    
<div class="success">
<h3 id="pythonlog2-checkscaffold">Check Scaffold for Assignment 2</h3>
<pre><code>Guessing ListEQ.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog2-runanswer">Run Answer for Assignment 2</h3>
<pre><code>Guessing ListEQ.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/2-ListEQ/python_answer/ListEQ.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/2-ListEQ/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog3" class="logdetails">
      <h2>Assignment 3 full log</h2>
    
<div class="success">
<h3 id="pythonlog3-checkscaffold">Check Scaffold for Assignment 3</h3>
<pre><code>Guessing GraphBaconNumber.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog3-runanswer">Run Answer for Assignment 3</h3>
<pre><code>Guessing GraphBaconNumber.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/3-GraphBaconNumber/python_answer/GraphBaconNumber.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/3-GraphBaconNumber/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog4" class="logdetails">
      <h2>Assignment 4 full log</h2>
    
<div class="success">
<h3 id="pythonlog4-checkscaffold">Check Scaffold for Assignment 4</h3>
<pre><code>Guessing GraphEQ.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog4-runanswer">Run Answer for Assignment 4</h3>
<pre><code>Guessing GraphEQ.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/4-GraphEQ/python_answer/GraphEQ.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/4-GraphEQ/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog5" class="logdetails">
      <h2>Assignment 5 full log</h2>
    
<div class="success">
<h3 id="pythonlog5-checkscaffold">Check Scaffold for Assignment 5</h3>
<pre><code>Guessing bst_eq.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog5-runanswer">Run Answer for Assignment 5</h3>
<pre><code>Guessing bst_eq.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/5-BST_Earthquakes/python_answer/bst_eq.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/5-BST_Earthquakes/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog6" class="logdetails">
      <h2>Assignment 6 full log</h2>
    
<div class="success">
<h3 id="pythonlog6-checkscaffold">Check Scaffold for Assignment 6</h3>
<pre><code>Guessing GridSquareFill.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog6-runanswer">Run Answer for Assignment 6</h3>
<pre><code>Guessing GridSquareFill.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/6-GridSquareFill/python_answer/GridSquareFill.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/6-GridSquareFill/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog7" class="logdetails">
      <h2>Assignment 7 full log</h2>
    
<div class="success">
<h3 id="pythonlog7-checkscaffold">Check Scaffold for Assignment 7</h3>
<pre><code>Guessing GridLyrics.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog7-runanswer">Run Answer for Assignment 7</h3>
<pre><code>Guessing GridLyrics.py is the python file where main is

/home/bridges-testing/bridges-assignments/assignmentdb/7-GridLyrics/python_answer/GridLyrics.py:9: SyntaxWarning: invalid escape sequence '\('
  lyrics = re.sub('[\(\[].*?[\)\]]', '', lyrics)
Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/7-GridLyrics/python_answer/GridLyrics.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/7-GridLyrics/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog8" class="logdetails">
      <h2>Assignment 8 full log</h2>
    
<div class="success">
<h3 id="pythonlog8-checkscaffold">Check Scaffold for Assignment 8</h3>
<pre><code>Guessing PQBook.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog8-runanswer">Run Answer for Assignment 8</h3>
<pre><code>Guessing PQBook.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/8-PQBook/python_answer/PQBook.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/8-PQBook/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog9" class="logdetails">
      <h2>Assignment 9 full log</h2>
    
<div class="success">
<h3 id="pythonlog9-checkscaffold">Check Scaffold for Assignment 9</h3>
<pre><code>Guessing ShortestPathOSM.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog9-runanswer">Run Answer for Assignment 9</h3>
<pre><code>Guessing ShortestPathOSM.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/9-ShortestPathOSM/python_answer/ShortestPathOSM.py&quot;, line 1, in &lt;module&gt;
    from bridges.color import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/9-ShortestPathOSM/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog10" class="logdetails">
      <h2>Assignment 10 full log</h2>
    
<div class="success">
<h3 id="pythonlog10-checkscaffold">Check Scaffold for Assignment 10</h3>
<pre><code>Guessing HurricaneTracker.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog10-runanswer">Run Answer for Assignment 10</h3>
<pre><code>Guessing HurricaneTracker.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/10-HurricaneTracker/python_answer/HurricaneTracker.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/10-HurricaneTracker/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog11" class="logdetails">
      <h2>Assignment 11 full log</h2>
    
<div class="success">
<h3 id="pythonlog11-checkscaffold">Check Scaffold for Assignment 11</h3>
<pre><code>Guessing 2048Game.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog11-runanswer">Run Answer for Assignment 11</h3>
<pre><code>Guessing 2048Game.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/11-2048Game/python_answer/2048Game.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/11-2048Game/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog12" class="logdetails">
      <h2>Assignment 12 full log</h2>
    
<div class="success">
<h3 id="pythonlog12-checkscaffold">Check Scaffold for Assignment 12</h3>
<pre><code>Guessing AStarMaze.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog12-runanswer">Run Answer for Assignment 12</h3>
<pre><code>Guessing AStarMaze.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/12-AStarMaze/python_answer/AStarMaze.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/12-AStarMaze/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog13" class="logdetails">
      <h2>Assignment 13 full log</h2>
    
<div class="success">
<h3 id="pythonlog13-checkscaffold">Check Scaffold for Assignment 13</h3>
<pre><code>Guessing InfiniteRunner.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog13-runanswer">Run Answer for Assignment 13</h3>
<pre><code>Guessing InfiniteRunner.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/13-InfiniteRunner/python_answer/InfiniteRunner.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/13-InfiniteRunner/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog14" class="logdetails">
      <h2>Assignment 14 full log</h2>
    
<div class="success">
<h3 id="pythonlog14-checkscaffold">Check Scaffold for Assignment 14</h3>
<pre><code>Guessing SpreadingFire.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog14-runanswer">Run Answer for Assignment 14</h3>
<pre><code>Guessing SpreadingFire.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/14-SpreadingFire/python_answer/SpreadingFire.py&quot;, line 3, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/14-SpreadingFire/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog15" class="logdetails">
      <h2>Assignment 15 full log</h2>
    
<div class="success">
<h3 id="pythonlog15-checkscaffold">Check Scaffold for Assignment 15</h3>
<pre><code>Guessing FallingSand.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog15-runanswer">Run Answer for Assignment 15</h3>
<pre><code>Guessing FallingSand.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/15-FallingSand/python_answer/FallingSand.py&quot;, line 3, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/15-FallingSand/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog16" class="logdetails">
      <h2>Assignment 16 full log</h2>
    
<div class="success">
<h3 id="pythonlog16-checkscaffold">Check Scaffold for Assignment 16</h3>
<pre><code>Guessing ImagePuzzle.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog16-runanswer">Run Answer for Assignment 16</h3>
<pre><code>Guessing ImagePuzzle.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/16-ImagePuzzle/python_answer/ImagePuzzle.py&quot;, line 1, in &lt;module&gt;
    from bridges import *;
    ^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/16-ImagePuzzle/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog17" class="logdetails">
      <h2>Assignment 17 full log</h2>
    
<div class="success">
<h3 id="pythonlog17-checkscaffold">Check Scaffold for Assignment 17</h3>
<pre><code>Guessing ControlsTutorial.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog17-runanswer">Run Answer for Assignment 17</h3>
<pre><code>Guessing ControlsTutorial.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/17-ControlsTutorial/python_answer/ControlsTutorial.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/17-ControlsTutorial/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog18" class="logdetails">
      <h2>Assignment 18 full log</h2>
    
<div class="success">
<h3 id="pythonlog18-checkscaffold">Check Scaffold for Assignment 18</h3>
<pre><code>Guessing ControlsTutorialTwo.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog18-runanswer">Run Answer for Assignment 18</h3>
<pre><code>Guessing ControlsTutorialTwo.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/18-ControlsTutorialTwo/python_answer/ControlsTutorialTwo.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/18-ControlsTutorialTwo/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog19" class="logdetails">
      <h2>Assignment 19 full log</h2>
    
<div class="success">
<h3 id="pythonlog19-checkscaffold">Check Scaffold for Assignment 19</h3>
<pre><code>Guessing BUGSTOMP.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog19-runanswer">Run Answer for Assignment 19</h3>
<pre><code>Guessing BUGSTOMP.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/19-Bugstomp/python_answer/BUGSTOMP.py&quot;, line 3, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/19-Bugstomp/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog20" class="logdetails">
      <h2>Assignment 20 full log</h2>
    
<div class="success">
<h3 id="pythonlog20-checkscaffold">Check Scaffold for Assignment 20</h3>
<pre><code>Guessing minesweeper.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog20-runanswer">Run Answer for Assignment 20</h3>
<pre><code>Guessing minesweeper.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/20-Minesweeper/python_answer/minesweeper.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/20-Minesweeper/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog21" class="logdetails">
      <h2>Assignment 21 full log</h2>
    
<div class="success">
<h3 id="pythonlog21-checkscaffold">Check Scaffold for Assignment 21</h3>
<pre><code>Guessing RaceCar.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog21-runanswer">Run Answer for Assignment 21</h3>
<pre><code>Guessing RaceCar.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/21-RaceCar/python_answer/RaceCar.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/21-RaceCar/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog22" class="logdetails">
      <h2>Assignment 22 full log</h2>
    
<div class="success">
<h3 id="pythonlog22-checkscaffold">Check Scaffold for Assignment 22</h3>
<pre><code>Guessing Snake.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog22-runanswer">Run Answer for Assignment 22</h3>
<pre><code>Guessing Snake.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/22-Snake/python_answer/Snake.py&quot;, line 3, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/22-Snake/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog23" class="logdetails">
      <h2>Assignment 23 full log</h2>
    
<div class="success">
<h3 id="pythonlog23-checkscaffold">Check Scaffold for Assignment 23</h3>
<pre><code>Guessing MountainPaths.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog23-runanswer">Run Answer for Assignment 23</h3>
<pre><code>Guessing MountainPaths.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/23-MountainPaths/python_answer/MountainPaths.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/23-MountainPaths/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog24" class="logdetails">
      <h2>Assignment 24 full log</h2>
    
<div class="success">
<h3 id="pythonlog24-checkscaffold">Check Scaffold for Assignment 24</h3>
<pre><code>Guessing ImageCompressionKdTree.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog24-runanswer">Run Answer for Assignment 24</h3>
<pre><code>Guessing ImageCompressionKdTree.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/24-ImageCompressionKdTree/python_answer/ImageCompressionKdTree.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/24-ImageCompressionKdTree/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog25" class="logdetails">
      <h2>Assignment 25 full log</h2>
    
<div class="success">
<h3 id="pythonlog25-checkscaffold">Check Scaffold for Assignment 25</h3>
<pre><code>Guessing Patterns.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog25-runanswer">Run Answer for Assignment 25</h3>
<pre><code>Guessing Patterns.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/25-Patterns/python_answer/Patterns.py&quot;, line 1, in &lt;module&gt;
    from bridges import *;
    ^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/25-Patterns/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog26" class="logdetails">
      <h2>Assignment 26 full log</h2>
    
<div class="success">
<h3 id="pythonlog26-checkscaffold">Check Scaffold for Assignment 26</h3>
<pre><code>Guessing TowersOfHanoi.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog26-runanswer">Run Answer for Assignment 26</h3>
<pre><code>Guessing TowersOfHanoi.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/26-TowersOfHanoi/python_answer/TowersOfHanoi.py&quot;, line 2, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/26-TowersOfHanoi/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog27" class="logdetails">
      <h2>Assignment 27 full log</h2>
    
<div class="success">
<h3 id="pythonlog27-checkscaffold">Check Scaffold for Assignment 27</h3>
<pre><code>Guessing GameGridAdvanced.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog27-runanswer">Run Answer for Assignment 27</h3>
<pre><code>Guessing GameGridAdvanced.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/27-GameGridBasic/python_answer/GameGridAdvanced.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/27-GameGridBasic/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog28" class="logdetails">
      <h2>Assignment 28 full log</h2>
    
<div class="success">
<h3 id="pythonlog28-checkscaffold">Check Scaffold for Assignment 28</h3>
<pre><code>Guessing BigOhMatters.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog28-runanswer">Run Answer for Assignment 28</h3>
<pre><code>Guessing BigOhMatters.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/28-BigOhMatters/python_answer/BigOhMatters.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/28-BigOhMatters/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog29" class="logdetails">
      <h2>Assignment 29 full log</h2>
    
<div class="success">
<h3 id="pythonlog29-checkscaffold">Check Scaffold for Assignment 29</h3>
<pre><code>Guessing SortingBenchmark.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog29-runanswer">Run Answer for Assignment 29</h3>
<pre><code>Guessing SortingBenchmark.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/29-SortingBenchmark/python_answer/SortingBenchmark.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/29-SortingBenchmark/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog30" class="logdetails">
      <h2>Assignment 30 full log</h2>
    
<div class="failure">
<h3 id="pythonlog30-checkscaffold">Check Scaffold for Assignment 30</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/30-TemporalBaconNumber/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog30-runanswer">Run Answer for Assignment 30</h3>
<pre><code>Guessing TemporalBaconNumber.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/30-TemporalBaconNumber/python_answer/TemporalBaconNumber.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/30-TemporalBaconNumber/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog31" class="logdetails">
      <h2>Assignment 31 full log</h2>
    
<div class="failure">
<h3 id="pythonlog31-checkscaffold">Check Scaffold for Assignment 31</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/31-TemporalPageRank/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog31-runanswer">Run Answer for Assignment 31</h3>
<pre><code>Guessing TemporalPageRank.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/31-TemporalPageRank/python_answer/TemporalPageRank.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/31-TemporalPageRank/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog32" class="logdetails">
      <h2>Assignment 32 full log</h2>
    
<div class="success">
<h3 id="pythonlog32-checkscaffold">Check Scaffold for Assignment 32</h3>
<pre><code>Guessing tic_tac_toe.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog32-runanswer">Run Answer for Assignment 32</h3>
<pre><code>Guessing tic_tac_toe.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/32-TicTacToe/python_answer/tic_tac_toe.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/32-TicTacToe/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog33" class="logdetails">
      <h2>Assignment 33 full log</h2>
    
<div class="success">
<h3 id="pythonlog33-checkscaffold">Check Scaffold for Assignment 33</h3>
<pre><code>Guessing audio_mixing.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog33-runanswer">Run Answer for Assignment 33</h3>
<pre><code>Guessing audio_mixing.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/33-AudioMixing/python_answer/audio_mixing.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/33-AudioMixing/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog34" class="logdetails">
      <h2>Assignment 34 full log</h2>
    
<div class="success">
<h3 id="pythonlog34-checkscaffold">Check Scaffold for Assignment 34</h3>
<pre><code>Guessing GameTutorial.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog34-runanswer">Run Answer for Assignment 34</h3>
<pre><code>Guessing GameTutorial.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/34-GameTutorials/python_answer/GameTutorial.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/34-GameTutorials/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog35" class="logdetails">
      <h2>Assignment 35 full log</h2>
    
<div class="success">
<h3 id="pythonlog35-checkscaffold">Check Scaffold for Assignment 35</h3>
<pre><code>Guessing connect_four.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog35-runanswer">Run Answer for Assignment 35</h3>
<pre><code>Guessing connect_four.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/35-ConnectFour/python_answer/connect_four.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/35-ConnectFour/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog36" class="logdetails">
      <h2>Assignment 36 full log</h2>
    
<div class="success">
<h3 id="pythonlog36-checkscaffold">Check Scaffold for Assignment 36</h3>
<pre><code>Guessing pong.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog36-runanswer">Run Answer for Assignment 36</h3>
<pre><code>Guessing pong.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/36-Pong/python_answer/pong.py&quot;, line 1, in &lt;module&gt;
    from bridges import NamedColor
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/36-Pong/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog37" class="logdetails">
      <h2>Assignment 37 full log</h2>
    
<div class="success">
<h3 id="pythonlog37-checkscaffold">Check Scaffold for Assignment 37</h3>
<pre><code>Guessing bitdepth.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog37-runanswer">Run Answer for Assignment 37</h3>
<pre><code>Guessing bitdepth.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/37-SubsamplingBitdepth/python_answer/bitdepth.py&quot;, line 1, in &lt;module&gt;
    from bridges import AudioClip, Bridges
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/37-SubsamplingBitdepth/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog38" class="logdetails">
      <h2>Assignment 38 full log</h2>
    
<div class="success">
<h3 id="pythonlog38-checkscaffold">Check Scaffold for Assignment 38</h3>
<pre><code>Guessing geological_survey.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog38-runanswer">Run Answer for Assignment 38</h3>
<pre><code>Guessing geological_survey.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/38-GeologicalSurvey/python_answer/geological_survey.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/38-GeologicalSurvey/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog39" class="logdetails">
      <h2>Assignment 39 full log</h2>
    
<div class="failure">
<h3 id="pythonlog39-checkscaffold">Check Scaffold for Assignment 39</h3>
<pre><code>can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog39-runanswer">Run Answer for Assignment 39</h3>
<pre><code>Guessing BookDistance.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/39-BookDistance/python_answer/BookDistance.py&quot;, line 1, in &lt;module&gt;
    from bridges import graph_adj_list
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/39-BookDistance/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog40" class="logdetails">
      <h2>Assignment 40 full log</h2>
    
<div class="success">
<h3 id="pythonlog40-checkscaffold">Check Scaffold for Assignment 40</h3>
<pre><code>Guessing image_process.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog40-runanswer">Run Answer for Assignment 40</h3>
<pre><code>Guessing image_process.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/40-ImageProcessing/python_answer/image_process.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/40-ImageProcessing/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog41" class="logdetails">
      <h2>Assignment 41 full log</h2>
    
<div class="success">
<h3 id="pythonlog41-checkscaffold">Check Scaffold for Assignment 41</h3>
<pre><code>Guessing SpaceInvaders.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog41-runanswer">Run Answer for Assignment 41</h3>
<pre><code>Guessing SpaceInvaders.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/41-SpaceInvaders/python_answer/SpaceInvaders.py&quot;, line 2, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/41-SpaceInvaders/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog42" class="logdetails">
      <h2>Assignment 42 full log</h2>
    
<div class="success">
<h3 id="pythonlog42-checkscaffold">Check Scaffold for Assignment 42</h3>
<pre><code>Guessing Covid.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog42-runanswer">Run Answer for Assignment 42</h3>
<pre><code>Guessing covid.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/42-Covid/python_answer/covid.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/42-Covid/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog43" class="logdetails">
      <h2>Assignment 43 full log</h2>
    
<div class="success">
<h3 id="pythonlog43-checkscaffold">Check Scaffold for Assignment 43</h3>
<pre><code>Guessing spatialindexing.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog43-runanswer">Run Answer for Assignment 43</h3>
<pre><code>Guessing spatialindexing.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/43-SpatialIndexing/python_answer/spatialindexing.py&quot;, line 2, in &lt;module&gt;
    from bridges.color import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/43-SpatialIndexing/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog44" class="logdetails">
      <h2>Assignment 44 full log</h2>
    
<div class="success">
<h3 id="pythonlog44-checkscaffold">Check Scaffold for Assignment 44</h3>
<pre><code>Guessing prim_mst_cities.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog44-runanswer">Run Answer for Assignment 44</h3>
<pre><code>Guessing prim_mst_cities.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/44-MST-Cities/python_answer/prim_mst_cities.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/44-MST-Cities/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog45" class="logdetails">
      <h2>Assignment 45 full log</h2>
    
<div class="success">
<h3 id="pythonlog45-checkscaffold">Check Scaffold for Assignment 45</h3>
<pre><code>Guessing ExplorerRobot.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog45-runanswer">Run Answer for Assignment 45</h3>
<pre><code>Guessing ExplorerRobot.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/45-ExplorerRobot/python_answer/ExplorerRobot.py&quot;, line 2, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/45-ExplorerRobot/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog46" class="logdetails">
      <h2>Assignment 46 full log</h2>
    
<div class="failure">
<h3 id="pythonlog46-checkscaffold">Check Scaffold for Assignment 46</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/46-AirBNB/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog46-runanswer">Run Answer for Assignment 46</h3>
<pre><code>assignment 46 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog47" class="logdetails">
      <h2>Assignment 47 full log</h2>
    
<div class="failure">
<h3 id="pythonlog47-checkscaffold">Check Scaffold for Assignment 47</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/47-Impressionism_Art/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog47-runanswer">Run Answer for Assignment 47</h3>
<pre><code>assignment 47 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog48" class="logdetails">
      <h2>Assignment 48 full log</h2>
    
<div class="failure">
<h3 id="pythonlog48-checkscaffold">Check Scaffold for Assignment 48</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/48-MediaCollage/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog48-runanswer">Run Answer for Assignment 48</h3>
<pre><code>assignment 48 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog49" class="logdetails">
      <h2>Assignment 49 full log</h2>
    
<div class="failure">
<h3 id="pythonlog49-checkscaffold">Check Scaffold for Assignment 49</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/49-CharacterAnimation/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog49-runanswer">Run Answer for Assignment 49</h3>
<pre><code>assignment 49 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog50" class="logdetails">
      <h2>Assignment 50 full log</h2>
    
<div class="failure">
<h3 id="pythonlog50-checkscaffold">Check Scaffold for Assignment 50</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/50-PoliceData/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog50-runanswer">Run Answer for Assignment 50</h3>
<pre><code>assignment 50 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog51" class="logdetails">
      <h2>Assignment 51 full log</h2>
    
<div class="failure">
<h3 id="pythonlog51-checkscaffold">Check Scaffold for Assignment 51</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/51-StereoSoundProcessing/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog51-runanswer">Run Answer for Assignment 51</h3>
<pre><code>assignment 51 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog52" class="logdetails">
      <h2>Assignment 52 full log</h2>
    
<div class="success">
<h3 id="pythonlog52-checkscaffold">Check Scaffold for Assignment 52</h3>
<pre><code>Guessing audioWave.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog52-runanswer">Run Answer for Assignment 52</h3>
<pre><code>Guessing audioWave.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/52-AudioWave/python_answer/audioWave.py&quot;, line 1, in &lt;module&gt;
    from bridges import AudioClip
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/52-AudioWave/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog53" class="logdetails">
      <h2>Assignment 53 full log</h2>
    
<div class="failure">
<h3 id="pythonlog53-checkscaffold">Check Scaffold for Assignment 53</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/53-DNA_Splicing/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog53-runanswer">Run Answer for Assignment 53</h3>
<pre><code>assignment 53 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog54" class="logdetails">
      <h2>Assignment 54 full log</h2>
    
<div class="failure">
<h3 id="pythonlog54-checkscaffold">Check Scaffold for Assignment 54</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/54-Starmap/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog54-runanswer">Run Answer for Assignment 54</h3>
<pre><code>assignment 54 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog55" class="logdetails">
      <h2>Assignment 55 full log</h2>
    
<div class="failure">
<h3 id="pythonlog55-checkscaffold">Check Scaffold for Assignment 55</h3>
<pre><code>grep: *py: No such file or directory
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog55-runanswer">Run Answer for Assignment 55</h3>
<pre><code>./testassignment_python.sh: 270: [: ../assignmentdb/55-FreqencyPlayer: unexpected operator
assignment 55 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog56" class="logdetails">
      <h2>Assignment 56 full log</h2>
    
<div class="success">
<h3 id="pythonlog56-checkscaffold">Check Scaffold for Assignment 56</h3>
<pre><code>Guessing layers.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog56-runanswer">Run Answer for Assignment 56</h3>
<pre><code>Guessing layers.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/56-2DIndexing/python_answer/layers.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/56-2DIndexing/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog57" class="logdetails">
      <h2>Assignment 57 full log</h2>
    
<div class="failure">
<h3 id="pythonlog57-checkscaffold">Check Scaffold for Assignment 57</h3>
<pre><code>can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog57-runanswer">Run Answer for Assignment 57</h3>
<pre><code>can't guess a python file
could not run python_answer for assignment in ../assignmentdb/57-BookAnalysis/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog58" class="logdetails">
      <h2>Assignment 58 full log</h2>
    
<div class="failure">
<h3 id="pythonlog58-checkscaffold">Check Scaffold for Assignment 58</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/58-WordCloud/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog58-runanswer">Run Answer for Assignment 58</h3>
<pre><code>assignment 58 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog59" class="logdetails">
      <h2>Assignment 59 full log</h2>
    
<div class="success">
<h3 id="pythonlog59-checkscaffold">Check Scaffold for Assignment 59</h3>
<pre><code>Guessing cvh.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog59-runanswer">Run Answer for Assignment 59</h3>
<pre><code>Guessing cvh.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/59-ConvexHull_CityData/python_answer/cvh.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/59-ConvexHull_CityData/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog60" class="logdetails">
      <h2>Assignment 60 full log</h2>
    
<div class="success">
<h3 id="pythonlog60-checkscaffold">Check Scaffold for Assignment 60</h3>
<pre><code>Guessing quadtree.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog60-runanswer">Run Answer for Assignment 60</h3>
<pre><code>Guessing quadtree.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/60-Quadtree-CityData/python_answer/quadtree.py&quot;, line 2, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/60-Quadtree-CityData/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog61" class="logdetails">
      <h2>Assignment 61 full log</h2>
    
<div class="success">
<h3 id="pythonlog61-checkscaffold">Check Scaffold for Assignment 61</h3>
<pre><code>Guessing main.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog61-runanswer">Run Answer for Assignment 61</h3>
<pre><code>Guessing flight.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/61-Flight-Data/python_answer/flight.py&quot;, line 5, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/61-Flight-Data/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog62" class="logdetails">
      <h2>Assignment 62 full log</h2>
    
<div class="success">
<h3 id="pythonlog62-checkscaffold">Check Scaffold for Assignment 62</h3>
<pre><code>Guessing flags.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog62-runanswer">Run Answer for Assignment 62</h3>
<pre><code>Guessing flags.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/62-Flags/python_answer/flags.py&quot;, line 1, in &lt;module&gt;
    from bridges.color_grid import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/62-Flags/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog63" class="logdetails">
      <h2>Assignment 63 full log</h2>
    
<div class="failure">
<h3 id="pythonlog63-checkscaffold">Check Scaffold for Assignment 63</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/63-ConvexHull2/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog63-runanswer">Run Answer for Assignment 63</h3>
<pre><code>grep: *py: No such file or directory
can't guess a python file
could not run python_answer for assignment in ../assignmentdb/63-ConvexHull2/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog64" class="logdetails">
      <h2>Assignment 64 full log</h2>
    
<div class="success">
<h3 id="pythonlog64-checkscaffold">Check Scaffold for Assignment 64</h3>
<pre><code>Guessing voronoi_diag.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog64-runanswer">Run Answer for Assignment 64</h3>
<pre><code>Guessing voronoi_diag.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/64-Voronoi_Diagram/python_answer/voronoi_diag.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/64-Voronoi_Diagram/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog65" class="logdetails">
      <h2>Assignment 65 full log</h2>
    
<div class="success">
<h3 id="pythonlog65-checkscaffold">Check Scaffold for Assignment 65</h3>
<pre><code>Guessing reddit.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog65-runanswer">Run Answer for Assignment 65</h3>
<pre><code>Guessing reddit.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/65-Reddit/python_answer/reddit.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/65-Reddit/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog66" class="logdetails">
      <h2>Assignment 66 full log</h2>
    
<div class="success">
<h3 id="pythonlog66-checkscaffold">Check Scaffold for Assignment 66</h3>
<pre><code>Guessing chess.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog66-runanswer">Run Answer for Assignment 66</h3>
<pre><code>Guessing chess.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/66-Chess-Data/python_answer/chess.py&quot;, line 3, in &lt;module&gt;
    from bridges import GraphAdjList, Bridges
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/66-Chess-Data/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog67" class="logdetails">
      <h2>Assignment 67 full log</h2>
    
<div class="success">
<h3 id="pythonlog67-checkscaffold">Check Scaffold for Assignment 67</h3>
<pre><code>Guessing ControlsTutorial.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog67-runanswer">Run Answer for Assignment 67</h3>
<pre><code>Guessing ControlsTutorialThree.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/67-ControlsTutorialThree/python_answer/ControlsTutorialThree.py&quot;, line 1, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/67-ControlsTutorialThree/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog68" class="logdetails">
      <h2>Assignment 68 full log</h2>
    
<div class="success">
<h3 id="pythonlog68-checkscaffold">Check Scaffold for Assignment 68</h3>
<pre><code>Guessing musicNotes.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog68-runanswer">Run Answer for Assignment 68</h3>
<pre><code>Guessing musicNotes.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/68-MusicNotes-CS2/python_answer/musicNotes.py&quot;, line 1, in &lt;module&gt;
    from bridges import Bridges, AudioClip
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/68-MusicNotes-CS2/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog69" class="logdetails">
      <h2>Assignment 69 full log</h2>
    
<div class="success">
<h3 id="pythonlog69-checkscaffold">Check Scaffold for Assignment 69</h3>
<pre><code>Guessing Snake.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog69-runanswer">Run Answer for Assignment 69</h3>
<pre><code>Guessing Snake.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/69-SnakeQueue/python_answer/Snake.py&quot;, line 1, in &lt;module&gt;
    from bridges.non_blocking_game import NonBlockingGame
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/69-SnakeQueue/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog70" class="logdetails">
      <h2>Assignment 70 full log</h2>
    
<div class="success">
<h3 id="pythonlog70-checkscaffold">Check Scaffold for Assignment 70</h3>
<pre><code>Guessing Wordle.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog70-runanswer">Run Answer for Assignment 70</h3>
<pre><code>Guessing Wordle.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/70-WordleBot/python_answer/Wordle.py&quot;, line 1, in &lt;module&gt;
    from bridges import NonBlockingGame
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/70-WordleBot/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog71" class="logdetails">
      <h2>Assignment 71 full log</h2>
    
<div class="success">
<h3 id="pythonlog71-checkscaffold">Check Scaffold for Assignment 71</h3>
<pre><code>Guessing pi_estimation.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog71-runanswer">Run Answer for Assignment 71</h3>
<pre><code>Guessing Pi_Estimation.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/71-PiEstimation/python_answer/Pi_Estimation.py&quot;, line 1, in &lt;module&gt;
    from bridges.color_grid import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/71-PiEstimation/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog72" class="logdetails">
      <h2>Assignment 72 full log</h2>
    
<div class="success">
<h3 id="pythonlog72-checkscaffold">Check Scaffold for Assignment 72</h3>
<pre><code>Guessing pixel.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog72-runanswer">Run Answer for Assignment 72</h3>
<pre><code>Guessing pixel.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/72-PixelDrawing/python_answer/pixel.py&quot;, line 2, in &lt;module&gt;
    import bridges
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/72-PixelDrawing/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog73" class="logdetails">
      <h2>Assignment 73 full log</h2>
    
<div class="success">
<h3 id="pythonlog73-checkscaffold">Check Scaffold for Assignment 73</h3>
<pre><code>Guessing encoding.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog73-runanswer">Run Answer for Assignment 73</h3>
<pre><code>Guessing encoding.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/73-ColorEncoding/python_answer/encoding.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/73-ColorEncoding/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog74" class="logdetails">
      <h2>Assignment 74 full log</h2>
    
<div class="failure">
<h3 id="pythonlog74-checkscaffold">Check Scaffold for Assignment 74</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/74-Fractals/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog74-runanswer">Run Answer for Assignment 74</h3>
<pre><code>assignment 74 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog75" class="logdetails">
      <h2>Assignment 75 full log</h2>
    
<div class="success">
<h3 id="pythonlog75-checkscaffold">Check Scaffold for Assignment 75</h3>
<pre><code>Guessing koch.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog75-runanswer">Run Answer for Assignment 75</h3>
<pre><code>Guessing koch.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/75-KochCurve/python_answer/koch.py&quot;, line 1, in &lt;module&gt;
    from bridges import Polyline, SymbolCollection, Bridges
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/75-KochCurve/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog76" class="logdetails">
      <h2>Assignment 76 full log</h2>
    
<div class="success">
<h3 id="pythonlog76-checkscaffold">Check Scaffold for Assignment 76</h3>
<pre><code>Guessing Zcurve.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog76-runanswer">Run Answer for Assignment 76</h3>
<pre><code>Guessing Zcurve.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/76-Zcurve/python_answer/Zcurve.py&quot;, line 1, in &lt;module&gt;
    from bridges.symbol_collection import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/76-Zcurve/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog77" class="logdetails">
      <h2>Assignment 77 full log</h2>
    
<div class="failure">
<h3 id="pythonlog77-checkscaffold">Check Scaffold for Assignment 77</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/77-UpgradeGame/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog77-runanswer">Run Answer for Assignment 77</h3>
<pre><code>assignment 77 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog78" class="logdetails">
      <h2>Assignment 78 full log</h2>
    
<div class="failure">
<h3 id="pythonlog78-checkscaffold">Check Scaffold for Assignment 78</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/78-Thresholding/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog78-runanswer">Run Answer for Assignment 78</h3>
<pre><code>can't guess a python file
could not run python_answer for assignment in ../assignmentdb/78-Thresholding/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog79" class="logdetails">
      <h2>Assignment 79 full log</h2>
    
<div class="failure">
<h3 id="pythonlog79-checkscaffold">Check Scaffold for Assignment 79</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/79-InstrumentCreation/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog79-runanswer">Run Answer for Assignment 79</h3>
<pre><code>assignment 79 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog80" class="logdetails">
      <h2>Assignment 80 full log</h2>
    
<div class="failure">
<h3 id="pythonlog80-checkscaffold">Check Scaffold for Assignment 80</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/80-Compression/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog80-runanswer">Run Answer for Assignment 80</h3>
<pre><code>assignment 80 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog81" class="logdetails">
      <h2>Assignment 81 full log</h2>
    
<div class="failure">
<h3 id="pythonlog81-checkscaffold">Check Scaffold for Assignment 81</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to ../assignmentdb/81-VisualizeAudio/python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog81-runanswer">Run Answer for Assignment 81</h3>
<pre><code>assignment 81 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog82" class="logdetails">
      <h2>Assignment 82 full log</h2>
    
<div class="failure">
<h3 id="pythonlog82-checkscaffold">Check Scaffold for Assignment 82</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to /python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog82-runanswer">Run Answer for Assignment 82</h3>
<pre><code>assignment 82 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog83" class="logdetails">
      <h2>Assignment 83 full log</h2>
    
<div class="failure">
<h3 id="pythonlog83-checkscaffold">Check Scaffold for Assignment 83</h3>
<pre><code>./testassignment_python.sh: 72: cd: can't cd to /python
can't guess a python file
</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog83-runanswer">Run Answer for Assignment 83</h3>
<pre><code>assignment 83 has no python_answer directory
</code></pre>
</div>
    
    </div>
    <div id="pythonlog84" class="logdetails">
      <h2>Assignment 84 full log</h2>
    
<div class="success">
<h3 id="pythonlog84-checkscaffold">Check Scaffold for Assignment 84</h3>
<pre><code>Guessing Energy.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog84-runanswer">Run Answer for Assignment 84</h3>
<pre><code>Guessing Energy.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/84-Energy/python_answer/Energy.py&quot;, line 3, in &lt;module&gt;
    from bridges import *
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/84-Energy/python_answer
</code></pre>
</div>
    
    </div>
    <div id="pythonlog85" class="logdetails">
      <h2>Assignment 85 full log</h2>
    
<div class="success">
<h3 id="pythonlog85-checkscaffold">Check Scaffold for Assignment 85</h3>
<pre><code>Guessing forest.py is the python file where main is

</code></pre>
</div>
<div class="failure">
<h3 id="pythonlog85-runanswer">Run Answer for Assignment 85</h3>
<pre><code>Guessing forest.py is the python file where main is

Traceback (most recent call last):
  File &quot;/home/bridges-testing/bridges-assignments/assignmentdb/85-ForestCov/python_answer/forest.py&quot;, line 1, in &lt;module&gt;
    from bridges.bridges import Bridges
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/__init__.py&quot;, line 1, in &lt;module&gt;
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1360, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1322, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1262, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1528, in find_spec
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1502, in _get_spec
  File &quot;&lt;frozen zipimport&gt;&quot;, line 111, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 675, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 822, in spec_from_file_location
  File &quot;&lt;frozen zipimport&gt;&quot;, line 170, in get_filename
  File &quot;&lt;frozen zipimport&gt;&quot;, line 708, in _get_module_code
  File &quot;&lt;frozen zipimport&gt;&quot;, line 637, in _compile_source
  File &quot;/home/bridges-testing/.local/lib/python3.12/site-packages/bridges-3.4.5.dev2-py3.12.egg/bridges/data_src_dependent/data_source.py&quot;, line 280
    return get_us_map_county_data(all_states, True)
IndentationError: unexpected indent
could not run python_answer for assignment in ../assignmentdb/85-ForestCov/python_answer
</code></pre>
</div>
    
    </div>
  </body>
